apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprocache
  namespace: vproproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vprocache
  template:
    metadata:
      labels:
        app: vprocache
    spec:
      containers:
      - name: vprocache
        image: salwansaied/vroproject:mc
        ports:
        - containerPort: 11211
          name: memcache-port
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: 11211
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
      initContainers:
      - name: init-memcached
        image: busybox:1.35
        command: ['sh', '-c', 'echo "Waiting for resources to be ready..."; sleep 5']
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache-service
  namespace: vproproject
spec:
  selector:
    app: vprocache
  ports:
  - port: 11211
    targetPort: memcache-port
