apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: vproproject
type: Opaque
data:
  # admin123 encoded in base64
  root-password: YWRtaW4xMjM=
  db-password: YWRtaW4xMjM=
  db-user: YWRtaW4=
  db-name: YWNjb3VudHM=
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: vproproject
type: Opaque
data:
  # test encoded in base64
  rabbitmq-user: dGVzdA==
  rabbitmq-password: dGVzdA==
