apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-sc
  namespace: vproproject
annotations:
  openebs.io/cas-type: local
  cas.openebs.io/config: |
    - name: StorageType
      value: "hostpath"
    - name: BasePath
      value: "/var/openebs/local"
provisioner: openebs.io/local
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodb-pvc
  namespace: vproproject
spec:
  storageClassName: openebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vpromq-pvc
  namespace: vproproject
spec:
  storageClassName: openebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
